services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reddit_scraper_bot
    volumes:
      - .:/usr/src/app
    command: ["python", "python_files/current_version/main.py"]
